name: Publish release on push

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create "${{ github.ref_name }}" --draft=false
